// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CloudflareConfig {
    /**
     * Creates a new CloudflareConfig instance.
     * @param {Partial<CloudflareConfig>} [$$source = {}] - The source object to create the CloudflareConfig.
     */
    constructor($$source = {}) {
        if (!("preferred_ips" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["preferred_ips"] = [];
        }
        if (!("doh_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["doh_url"] = "";
        }
        if (!("auto_update" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_update"] = false;
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("warp_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["warp_enabled"] = false;
        }
        if (!("warp_socks_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["warp_socks_port"] = 0;
        }
        if (!("warp_endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["warp_endpoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudflareConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloudflareConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preferred_ips" in $$parsedSource) {
            $$parsedSource["preferred_ips"] = $$createField0_0($$parsedSource["preferred_ips"]);
        }
        return new CloudflareConfig(/** @type {Partial<CloudflareConfig>} */($$parsedSource));
    }
}

export class ECHProfile {
    /**
     * Creates a new ECHProfile instance.
     * @param {Partial<ECHProfile>} [$$source = {}] - The source object to create the ECHProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["config"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["discovery_domain"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["doh_upstream"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["auto_update"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ECHProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ECHProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ECHProfile(/** @type {Partial<ECHProfile>} */($$parsedSource));
    }
}

export class IPStats {
    /**
     * Creates a new IPStats instance.
     * @param {Partial<IPStats>} [$$source = {}] - The source object to create the IPStats.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("latency" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latency"] = "";
        }
        if (!("failures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failures"] = 0;
        }
        if (!("last_check" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_check"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IPStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPStats(/** @type {Partial<IPStats>} */($$parsedSource));
    }
}

export class ImportSummary {
    /**
     * Creates a new ImportSummary instance.
     * @param {Partial<ImportSummary>} [$$source = {}] - The source object to create the ImportSummary.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["added"] = 0;
        }
        if (!("overwritten" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["overwritten"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportSummary(/** @type {Partial<ImportSummary>} */($$parsedSource));
    }
}

export class SiteGroup {
    /**
     * Creates a new SiteGroup instance.
     * @param {Partial<SiteGroup>} [$$source = {}] - The source object to create the SiteGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["website"] = undefined;
        }
        if (!("domains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["domains"] = [];
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("upstream" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upstream"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["upstreams"] = undefined;
        }
        if (!("sni_fake" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sni_fake"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * "", "tunnel_origin", "tunnel_upstream", "mitm", "direct"
             * @member
             * @type {string | undefined}
             */
            this["connect_policy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "", "auto", "original", "fake", "upstream", "none"
             * @member
             * @type {string | undefined}
             */
            this["sni_policy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "", "auto", "h1_only", "h2_h1"
             * @member
             * @type {string | undefined}
             */
            this["alpn_policy"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("ech_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ech_enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ech_profile_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Domain used for ECH DoH lookup
             * @member
             * @type {string | undefined}
             */
            this["ech_domain"] = undefined;
        }
        if (!("use_cf_pool" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["use_cf_pool"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SiteGroup}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domains" in $$parsedSource) {
            $$parsedSource["domains"] = $$createField3_0($$parsedSource["domains"]);
        }
        if ("upstreams" in $$parsedSource) {
            $$parsedSource["upstreams"] = $$createField6_0($$parsedSource["upstreams"]);
        }
        return new SiteGroup(/** @type {Partial<SiteGroup>} */($$parsedSource));
    }
}

export class Upstream {
    /**
     * Creates a new Upstream instance.
     * @param {Partial<Upstream>} [$$source = {}] - The source object to create the Upstream.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Upstream instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Upstream}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Upstream(/** @type {Partial<Upstream>} */($$parsedSource));
    }
}

export class WarpStatus {
    /**
     * Creates a new WarpStatus instance.
     * @param {Partial<WarpStatus>} [$$source = {}] - The source object to create the WarpStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("account" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WarpStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WarpStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WarpStatus(/** @type {Partial<WarpStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
