// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class InstalledCert {
    /**
     * Creates a new InstalledCert instance.
     * @param {Partial<InstalledCert>} [$$source = {}] - The source object to create the InstalledCert.
     */
    constructor($$source = {}) {
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("thumbprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thumbprint"] = "";
        }
        if (!("notAfter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notAfter"] = "";
        }
        if (!("storeName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storeName"] = "";
        }
        if (!("storeLocation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["storeLocation"] = "";
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledCert instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstalledCert}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstalledCert(/** @type {Partial<InstalledCert>} */($$parsedSource));
    }
}
