// @ts-ignore
import * as app from '../../bindings/snishaper/app.js';
import { Events } from '@wailsio/runtime';

export const EventsOn = (eventName: string, callback: (data: any) => void) =>
    Events.On(eventName, (event) => callback(event.data));
export const {
    AddSiteGroup,
    AddUpstream,
    ClearLogs,
    DeleteECHProfile,
    DeleteSiteGroup,
    DeleteUpstream,
    DisableSystemProxy,
    EnableSystemProxy,
    EnrollWarp,
    ExportCert,
    ExportConfig,
    FetchECHConfig,
    ForceFetchCloudflareIPs,
    GetCACertPEM,
    GetCACertPath,
    GetCAInstallStatus,
    GetCloseToTray,
    GetCloudflareConfig,
    GetCloudflareIPStats,
    GetECHProfiles,
    GetInstalledCerts,
    GetListenPort,
    GetProxyDiagnostics,
    GetProxyMode,
    GetRecentLogs,
    GetServerConfig,
    GetSiteGroups,
    GetStats,
    GetSystemProxyStatus,
    GetUpstreams,
    GetWarpStatus,
    Greet,
    HandleWindowClose,
    ImportConfig,
    ImportConfigWithSummary,
    InstallCA,
    IsProxyRunning,
    OpenCAFile,
    OpenCertDir,
    ProxySelfCheck,
    QuitApp,
    RefreshCloudflareIPPool,
    RegenerateCert,
    RegisterWarp,
    RemoveInvalidCFIPs,
    SetCloseToTray,
    SetListenPort,
    SetProxyMode,
    StartProxy,
    StartWarp,
    StopProxy,
    StopWarp,
    TriggerCFHealthCheck,
    UninstallCert,
    UpdateCloudflareConfig,
    UpdateServerConfig,
    UpdateSiteGroup,
    UpdateTrayMenu,
    UpdateUpstream,
    UpsertECHProfile,
    WindowClose,
    WindowMinimise,
    WindowToggleMaximise,
    GetAutoRoutingConfig,
    UpdateAutoRoutingConfig,
    GetAutoRoutingStatus,
    RefreshGFWList,
    TestServerNode
} = app;
