// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CAInstallStatus {
    /**
     * Creates a new CAInstallStatus instance.
     * @param {Partial<CAInstallStatus>} [$$source = {}] - The source object to create the CAInstallStatus.
     */
    constructor($$source = {}) {
        if (!("Installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Installed"] = false;
        }
        if (!("Platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Platform"] = "";
        }
        if (!("CertPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CertPath"] = "";
        }
        if (!("InstallHelp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["InstallHelp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CAInstallStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CAInstallStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CAInstallStatus(/** @type {Partial<CAInstallStatus>} */($$parsedSource));
    }
}

export class SystemProxyStatus {
    /**
     * Creates a new SystemProxyStatus instance.
     * @param {Partial<SystemProxyStatus>} [$$source = {}] - The source object to create the SystemProxyStatus.
     */
    constructor($$source = {}) {
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }
        if (!("Server" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Server"] = "";
        }
        if (!("Override" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Override"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemProxyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemProxyStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemProxyStatus(/** @type {Partial<SystemProxyStatus>} */($$parsedSource));
    }
}
